REMAINING_UNCOVERED_SEAM_PIXEL_COLOR = [253, 254, 255, 255]
BLOCKED_SEAM_PIXELS_COLOR = [63, 63, 63, 255]
ATTACHMENT_POINT_COLOR = [255, 0, 255, 255]

# TODO: should it depends on nr. of seam pixels? repeat (with hard limit) until certain percentage is covered?
NR_MAX_ATTEMPTS_PER_LAYER_TO_POPULATE_SINGLE_SEAM = 20  # 50
NR_MAX_DISTANCE_MOVING_TILE_INWARDS = 5  # 20
NEARBY_EDGE_PIXEL_SCAN_RADIUS = 8  # 8
MAXIMUM_SCAN_FOR_TRANSPARENCY_DISTANCE = 5  # 2
SEAM_DETECTION_SEARCH_RADIUS = 1
